// <auto-generated />
namespace Hammers.Inventory.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationmodififd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationmodififd));
        
        string IMigrationMetadata.Id
        {
            get { return "201608042039587_relationmodififd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
